CREATE TABLE characteristicReviews (
  ID SERIAL,
  CHARACTERISTIC_ID INT NOT NULL,
  REVIEW_ID INT NOT NULL,
  CHARACTERISTIC_VALUE INT NOT NULL
  PRIMARY KEY (ID),
  FOREIGN KEY (CHARACTERISTIC_ID) REFERENCES characteristics(ID),
  FOREIGN KEY (REVIEW_ID) REFERENCES reviews(ID)
);

COPY characteristicReviews(ID, CHARACTERISTIC_ID, REVIEW_ID, CHARACTERISTIC_VALUE)
FROM '/Users/timnevada/Documents/RFP57/sdc/RatingsAndReviews/csv_files/characteristics_reviews.csv'
DELIMITER ','
CSV HEADER;