CREATE SCHEMA ratingsAndReviews;

CREATE TABLE reviews (
  ID SERIAL,
  PRODUCT_ID INT,
  RATING INT NOT NULL,
  REVIEW_DATE TIMESTAMP(4),
  SUMMARY VARCHAR(300),
  BODY VARCHAR(1000),
  RECOMMENDED BOOLEAN,
  REPORTED BOOLEAN,
  REVIEWER_NAME VARCHAR(30),
  REVIEWER_EMAIL VARCHAR(50),
  RESPONSE VARCHAR(300),
  HELPFULNESS INT,
  PRIMARY KEY (ID)
);

COPY reviews(ID, PRODUCT_ID, RATING, REVIEW_DATE, SUMMARY, BODY, RECOMMENDED, REPORTED, REVIEWER_NAME, REVIEWER_EMAIL, RESPONSE, HELPFULNESS)
FROM '/Users/timnevada/Documents/RFP57/sdc/RatingsAndReviews/csv_files/reviews.csv'
DELIMITER ','
CSV HEADER;