CREATE SCHEMA ratingsAndReviews;

CREATE TABLE reviews (
  ID SERIAL,
  PRODUCT_ID INT NOT NULL,
  RATING INT NOT NULL,
  REVIEW_DATE TIMESTAMP,
  SUMMARY VARCHAR(300),
  BODY VARCHAR(1000),
  RECOMMENDED BOOLEAN,
  REPORTED BOOLEAN,
  REVIEWER_NAME VARCHAR(30),
  REVIEWER_EMAIL VARCHAR(50),
  RESPONSE VARCHAR(300),
  HELPFULNESS INT,
  PRIMARY KEY (ID)
);

CREATE TABLE reviewsPhotos (
  ID SERIAL,
  REVIEW_ID INT NOT NULL,
  PHOTO_URL VARCHAR(300),
  PRIMARY KEY (ID),
  FOREIGN KEY (REVIEW_ID) REFERENCES reviews(ID)
);

CREATE TABLE characteristicReviews (
  ID SERIAL,
  CHARACTERISTIC_ID INT NOT NULL,
  REVIEW_ID INT NOT NULL,
  CHARACTERISTIC_VALUE INT NOT NULL
  PRIMARY KEY (ID),
  FOREIGN KEY (CHARACTERISTIC_ID) REFERENCES characteristics(ID),
  FOREIGN KEY (REVIEW_ID) REFERENCES reviews(ID)
);

CREATE TABLE characteristics (
  ID SERIAL,
  PRODUCT_ID INT NOT NULL,
  CHARACTERISTIC_NAME VARCHAR(30),
  PRIMARY KEY (ID),
  FOREIGN KEY (PRODUCT_ID) REFERENCES reviews(PRODUCT_ID),
);

COPY reviews(ID, PRODUCT_ID, RATING, REVIEW_DATE, SUMMARY, BODY, RECOMMENDED, REPORTED, REVIEWER_NAME, REVIEWER_EMAIL, RESPONSE, HELPFULNESS)
FROM '/Users/timnevada/Documents/RFP57/sdc/RatingsAndReviews/csv_files/reviews.csv'
DELIMITER ','
CSV HEADER;

COPY reviewsPhotos(ID, REVIEW_ID, PHOTO_URL)
FROM '/Users/timnevada/Documents/RFP57/sdc/RatingsAndReviews/csv_files/reviews_photos.csv'
DELIMITER ','
CSV HEADER;

COPY characteristicReviews(ID, CHARACTERISTIC_ID, REVIEW_ID, CHARACTERISTIC_VALUE)
FROM '/Users/timnevada/Documents/RFP57/sdc/RatingsAndReviews/csv_files/characteristics_reviews.csv'
DELIMITER ','
CSV HEADER;

COPY characteristics(ID, PRODUCT_ID, CHARACTERISTIC_NAME)
FROM '/Users/timnevada/Documents/RFP57/sdc/RatingsAndReviews/csv_files/characteristics.csv'
DELIMITER ','
CSV HEADER;